data: /beegfs/ws/0/s4610340-energy_behavior/yahor/kaggle-predict_energy_behavior_of_prosumers/data
data_raw: ${dir.data}/raw
data_interim: ${dir.data}/interim
data_processed: ${dir.data}/processed
data_geo: ${dir.data_processed}/download_geo_data
data_stations: ${dir.data_processed}/prepare_stations
outputs: /beegfs/ws/0/s4610340-energy_behavior/yahor/kaggle-predict_energy_behavior_of_prosumers/outputs