_target_: predict_energy_behavior.models.joined_model.JoinedModel
_recursive_: True
model_p:
  _target_: predict_energy_behavior.models.production.two_orders_regression.TwoOrdersRegression
  _recursive_: True
  first_order_model:
    _target_: predict_energy_behavior.models.production.solar_output_regression.GroupedSolarOutputRegression
    group_columns:
      - "product_type"
    n_processes: 12
    regressors: 
      temperature: "temperature_historical"
      dewpoint: "dewpoint_historical"
      shortwave_radiation: "surface_solar_radiation_downwards_forecast"
      snowfall: "snowfall_historical"
      rain: "rain_historical"
      windspeed_10m: "windspeed_10m_historical"
      installed_capacity: "installed_capacity"
      
  second_order_model:
    _target_: predict_energy_behavior.models.production.second_order.LGBMSecondOrderModel
    n_models: 4
    n_jobs: 1
    n_gpus: 8
    parameters:
      n_estimators: 500
      learning_rate: 0.06
      colsample_bytree: 0.9
      colsample_bynode: 0.6
      reg_alpha: 3.5
      reg_lambda: 1.5
      max_depth: 12
      num_leaves: 400
      min_child_samples: 50
      objective: "regression_l1"
      device: "cpu"
      n_jobs: 12
      verbosity: 0
    features: [
      "temperature_historical",
      "dewpoint_historical",
      "rain_historical",
      "snowfall_historical",
      "cloudcover_total_historical",
      "cloudcover_low_historical",
      "cloudcover_mid_historical",
      "cloudcover_high_historical",
      "surface_solar_radiation_downwards_forecast",
      "windspeed_10m_historical",
      "10_metre_u_wind_component_historical",
      "10_metre_v_wind_component_historical",
      "hour",
      "dayofyear",
      "product_type",
      "is_business",
      # "installed_capacity",
      "predictions_first_order",
      "fog_historical"
    ]
model_c:
  _target_: predict_energy_behavior.models.consumption.lgbm_regression.LGBMOnMultiDiff
  _recursive_: True
  weights: [0.5, 0.5]
  models:
    - _target_: predict_energy_behavior.models.consumption.lgbm_regression.LGBMOnDiff
      diff_hours: 48
      n_models: 2
      n_gpus: 2
      n_jobs: 1
      features: [
        # "predictions_production",
        "product_type",
        "is_business",
        "weekday",
        "month",
        "dayofyear",
        "hour",
        # "eic_count",
        "is_country_holiday",
        # Historical diff 0h
        "diff_48h_temperature_historical",
        "diff_48h_dewpoint_historical",
        "diff_48h_rain_historical",
        "diff_48h_snowfall_historical",
        "diff_48h_cloudcover_total_historical",
        "diff_48h_windspeed_10m_historical",
        "diff_48h_surface_solar_radiation_downwards_forecast",
        "diff_48h_10_metre_u_wind_component_historical",
        "diff_48h_10_metre_v_wind_component_historical",
        "diff_48h_humidity_historical",
        # Target features
        "target_per_eic_diff_48h_lag48h",
        "target_per_eic_diff_48h_lag72h",
        "target_per_eic_diff_48h_lag96h",
        "target_per_eic_diff_48h_lag120h",
        "target_per_eic_diff_48h_lag144h",
        "target_per_eic_diff_48h_lag168h",
        "target_per_eic_diff_48h_median",
        "target_per_eic_diff_48h_q25",
        "target_per_eic_diff_48h_q75"
      ]

      parameters:
        n_estimators: 500
        learning_rate: 0.06
        colsample_bytree: 0.9
        colsample_bynode: 0.6
        reg_alpha: 3.5
        reg_lambda: 1.5
        max_depth: 16
        num_leaves: 500
        min_child_samples: 50
        objective: "regression_l1"
        device: "cpu"
        n_jobs: 12
        verbosity: 0
    - _target_: predict_energy_behavior.models.consumption.lgbm_regression.LGBMOnDiff
      diff_hours: 168
      n_models: 2
      n_gpus: 2
      n_jobs: 1
      features: [
        # "predictions_production",
        "product_type",
        "is_business",
        "weekday",
        "month",
        "dayofyear",
        "hour",
        # "eic_count",
        "is_country_holiday",
        # Historical diff 0h
        "diff_168h_temperature_historical",
        "diff_168h_dewpoint_historical",
        "diff_168h_rain_historical",
        "diff_168h_snowfall_historical",
        "diff_168h_cloudcover_total_historical",
        "diff_168h_windspeed_10m_historical",
        "diff_168h_surface_solar_radiation_downwards_forecast",
        "diff_168h_10_metre_u_wind_component_historical",
        "diff_168h_10_metre_v_wind_component_historical",
        "diff_168h_humidity_historical",
        # Target
        "target_per_eic_diff_168h_lag48h",
        "target_per_eic_diff_168h_lag72h",
        "target_per_eic_diff_168h_lag96h",
        "target_per_eic_diff_168h_lag120h",
        "target_per_eic_diff_168h_lag144h",
        "target_per_eic_diff_168h_lag168h",
        "target_per_eic_diff_168h_median",
        "target_per_eic_diff_168h_q25",
        "target_per_eic_diff_168h_q75",
      ]
      parameters:
        n_estimators: 500
        learning_rate: 0.06
        colsample_bytree: 0.9
        colsample_bynode: 0.6
        reg_alpha: 3.5
        reg_lambda: 1.5
        max_depth: 14
        num_leaves: 500
        min_child_samples: 50
        objective: "regression_l1"
        device: "cpu"
        n_jobs: 12
        verbosity: 0