# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: eb-inference
    chdir: true
  run:
    dir: ${dir.outputs}/${phase}/${hydra.job.override_dirname}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - dir: kaggle

phase: test

model:
  _target_: predict_energy_behavior.models.joined_model.JoinedModel.load
  path: /kaggle/input/enefit-pebop-model/model_joined

debug: False