# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: base-multi_order
    chdir: true
  run:
    dir: ${dir.outputs}/${phase}/${hydra.job.name}/${hydra.job.override_dirname}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - dir: alpha
  - split: temporal
  - model: multi_order

phase: train