# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: eb-${run_name}
    chdir: true
  run:
    dir: ${dir.outputs}/${phase}/${run_name}/${hydra.job.override_dirname}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - dir: alpha
  - cv: monthly_kfold
  - model: solar_out_and_diff-lgbms

phase: train
mlflow_tracking_uri: "http://172.26.122.53:5000/"
exp_name: eb/tune
run_name: cst+diff-lgbms-wo-extensive-reduce-compl